In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [3]:
TrainDF = pd.read_csv(Path('Resources/2019loans.csv'))
TestDF = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [9]:
# Convert categorical data to numeric and separate target feature for training data

#BinaryFlag For Yes or No for the Debt Settelment and Hardship Flag.
BinaryDict = {'Y':1, 'N':0}
TrainDF2 = TrainDF.replace({'hardship_flag':BinaryDict, 'debt_settlement_flag':BinaryDict})

#Home Owner ship Dictionary.
HomeOwnershipDict = {'ANY':0,'RENT':1,'MORTGAGE':2,'OWN':3}
TrainDF3 = TrainDF2.replace({'home_ownership':HomeOwnershipDict})

#Verification Status Disctionary.
VerificationStatusDict = {'Not Verified':0,'Source Verified':1,'Verified':1}
TrainDF4 = TrainDF3.replace({'verification_status':VerificationStatusDict})

#Get Loan Risk Status.
LoanRiskStatusDict = {'low_risk':1,'high_risk':0}
TrainDF5 = TrainDF4.replace({'loan_status':LoanRiskStatusDict})

#Get Initial List Status.
InitialListStatusDict = {'w':0,'f':1}
TrainDF6 = TrainDF5.replace({'initial_list_status':InitialListStatusDict})

#Get Application type.
ApplicationTypeDict = {'Individual':1,'Joint App':0}
TrainDF7 = TrainDF6.replace({'application_type':ApplicationTypeDict})

TrainDF8 = TrainDF7.drop(['index','pymnt_plan'],axis='columns')

FilePath = Path('Resources/cleaned_2019_credit_data.csv')
TrainDF8.to_csv(file_path, index=False)

TrainDF9 = TrainDF8.drop(['Unnamed: 0'],axis='columns')
TrainDF9.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,dti,delinq_2yrs,inq_last_6mths,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,13375.0,0.1797,483.34,2,223000.0,0,1,29.99,0.0,0.0,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,0,0
1,21000.0,0.1308,478.68,2,123000.0,1,1,11.26,2.0,0.0,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,0,0
2,20000.0,0.1240,448.95,2,197000.0,1,1,11.28,0.0,0.0,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,0,0
3,3000.0,0.1240,100.22,1,45000.0,0,1,18.08,0.0,0.0,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,0,0
4,30000.0,0.1612,1056.49,2,133000.0,1,1,27.77,0.0,2.0,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,0,0

In [17]:
X_train = TrainDF9.drop('loan_status', axis=1)
y_train = TrainDF9['loan_status'].values
print(f"{X_train.select_dtypes(include=[object])}")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[12180 rows x 0 columns]

In [18]:
# Convert categorical data to numeric and separate target feature for testing data
TrainDF2 = TrainDF.replace({'hardship_flag':BinaryDict, 'debt_settlement_flag':BinaryDict})
TrainDF3 = TrainDF2.replace({'home_ownership':HomeOwnershipDict})
TrainDF4 = TrainDF3.replace({'verification_status':VerificationStatusDict})
TrainDF5 = TrainDF4.replace({'loan_status':LoanRiskStatusDict})
TrainDF6 = TrainDF5.replace({'initial_list_status':InitialListStatusDict})
TrainDF7 = TrainDF6.replace({'application_type':ApplicationTypeDict})

TrainDF8 = TrainDF7.drop(['index','pymnt_plan'],axis='columns')

FilePath = Path('Resources/cleaned_2020_credit_data.csv')
TrainDF8.to_csv(file_path, index=False)

TrainDF9 = TrainDF8.drop(['Unnamed: 0'],axis='columns')
TrainDF9.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,dti,delinq_2yrs,inq_last_6mths,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,13375.0,0.1797,483.34,2,223000.0,0,1,29.99,0.0,0.0,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,0,0
1,21000.0,0.1308,478.68,2,123000.0,1,1,11.26,2.0,0.0,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,0,0
2,20000.0,0.1240,448.95,2,197000.0,1,1,11.28,0.0,0.0,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,0,0
3,3000.0,0.1240,100.22,1,45000.0,0,1,18.08,0.0,0.0,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,0,0
4,30000.0,0.1612,1056.49,2,133000.0,1,1,27.77,0.0,2.0,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,0,0

In [19]:
# add missing dummy variables to testing set
TrainDF10 = pd.get_dummies(TrainDF9)

X_test = TrainDF10.drop('loan_status', axis=1)
y_test = TrainDF10['loan_status'].values

In [20]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',max_iter=200)
classifier.fit(X_train, y_train)
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.6521346469622332
Testing Data Score: 0.6521346469622332

/Users/SM7_MacbookPro/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [23]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train, y_train)
print(f'Training Score: {clf.score(X_train, y_train)}')
print(f'Testing Score: {clf.score(X_test, y_test)}')

Training Score: 1.0
Testing Score: 1.0

In [28]:
# Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_TrainScaled = scaler.fit_transform(X_train)
X_TestScaled = scaler.fit_transform(X_test)

In [29]:
# Train the Logistic Regression model on the scaled data and print the model score
classifier.fit(X_train_scaled, y_train)
print(f"Training Data Score: {classifier.score(X_TrainScaled, y_train)}")
print(f"Testing Data Score: {classifier.score(X_TestScaled, y_test)}")

Training Data Score: 0.7061576354679803
Testing Data Score: 0.7061576354679803

/Users/SM7_MacbookPro/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [30]:
# Train a Random Forest Classifier model on the scaled data and print the model score
print(f'Random Model Score: {clf.score(X_test_scaled, y_test)}')

Random Model Score: 0.5